import type { MasterBuildPrompt } from "@/lib/types";

/**
 * Free per-project legal/support docs. In production these are generated once
 * and stored in Supabase storage with a public URL; here they're rendered on
 * demand as standalone hosted HTML pages.
 */
function shell(title: string, app: string, body: string): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} — ${app}</title>
<style>
  :root{--coral:#FF7A63;--cream:#FDFAF4;--ink:#2B2624;--soft:#5C534F}
  body{margin:0;background:var(--cream);color:var(--ink);
    font-family:ui-sans-serif,system-ui,sans-serif;line-height:1.65}
  .wrap{max-width:720px;margin:0 auto;padding:56px 24px}
  h1{font-size:2rem;margin:0 0 4px}
  .badge{display:inline-block;color:var(--coral);font-weight:600;font-size:.85rem}
  h2{margin-top:2rem;font-size:1.15rem}
  p,li{color:var(--soft)} a{color:var(--coral)}
  footer{margin-top:48px;font-size:.8rem;color:#8A807A}
</style></head><body><div class="wrap">
<span class="badge">${app}</span>
<h1>${title}</h1>
${body}
<footer>Generated by Appable · Last updated ${new Date().toISOString().slice(0, 10)}</footer>
</div></body></html>`;
}

export function legalDoc(
  doc: "privacy" | "terms" | "support",
  mp: MasterBuildPrompt
): string {
  const app = mp.appName;
  if (doc === "privacy") {
    return shell("Privacy Policy", app, `
      <p>${app} respects your privacy. This policy explains what we collect and why.</p>
      <h2>What we collect</h2>
      <p>Account info you provide and basic usage analytics to improve the app.</p>
      <h2>How we use it</h2>
      <p>To run ${app}, provide its features (${mp.features.join(", ")}), and keep it secure.</p>
      <h2>Your choices</h2>
      <p>You can request deletion of your data at any time via the support page.</p>
      <h2>Contact</h2>
      <p>Questions? Reach us through the in-app support page.</p>`);
  }
  if (doc === "terms") {
    return shell("Terms of Service", app, `
      <p>By using ${app}, you agree to these terms.</p>
      <h2>Using the app</h2>
      <p>Use ${app} lawfully and don't misuse its features.</p>
      <h2>Your content</h2>
      <p>You own your content; you grant us permission to operate the app.</p>
      <h2>Disclaimer</h2>
      <p>${app} is provided "as is" without warranties.</p>
      <h2>Changes</h2>
      <p>We may update these terms; continued use means acceptance.</p>`);
  }
  return shell("Support", app, `
    <p>Need a hand with ${app}? We're here to help.</p>
    <h2>Common questions</h2>
    <ul>
      <li>How do I get started? Open the app and follow the onboarding.</li>
      <li>How do I reset my account? Use the in-app settings.</li>
    </ul>
    <h2>Contact us</h2>
    <p>Email <a href="mailto:support@example.com">support@example.com</a> and we'll reply soon.</p>`);
}
