import type { MasterBuildPrompt } from "@/lib/types";

/**
 * Free per-project legal/support docs. In production these are generated once
 * and stored in Supabase storage with a public URL; here they're rendered on
 * demand as standalone hosted HTML pages.
 */
function shell(title: string, app: string, body: string): string {
  const year = new Date().getFullYear();
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} — ${app}</title>
<style>
  :root{--coral:#FF7A63;--cream:#FDFAF4;--ink:#2B2624;--soft:#5C534F}
  body{margin:0;background:var(--cream);color:var(--ink);
    font-family:ui-sans-serif,system-ui,sans-serif;line-height:1.65}
  .wrap{max-width:720px;margin:0 auto;padding:56px 24px}
  h1{font-size:2rem;margin:0 0 4px}
  .badge{display:inline-block;color:var(--coral);font-weight:600;font-size:.85rem}
  h2{margin-top:2rem;font-size:1.15rem;color:var(--ink)}
  p,li{color:var(--soft);font-size:.95rem}
  a{color:var(--coral)}
  footer{margin-top:48px;font-size:.8rem;color:#8A807A}
</style></head><body><div class="wrap">
<span class="badge">${app}</span>
<h1>${title}</h1>
${body}
<footer>© ${year} ${app} · Generated by Appable · Last updated ${new Date().toISOString().slice(0, 10)}</footer>
</div></body></html>`;
}

export function legalDoc(
  doc: "privacy" | "terms" | "support",
  mp: MasterBuildPrompt
): string {
  const app = mp.appName;
  const features = mp.features.join(", ");

  if (doc === "privacy") {
    return shell("Privacy Policy", app, `
      <p><strong>Effective date:</strong> ${new Date().toISOString().slice(0, 10)}</p>
      <p>${app} ("we," "us") respects your privacy. This policy describes what we collect, why we collect it, and the choices you have. It applies to the ${app} mobile application and related services built for ${mp.audience.toLowerCase()}.</p>

      <h2>Information we collect</h2>
      <ul>
        <li><strong>Account information</strong> — email, display name, and authentication identifiers when you create an account.</li>
        <li><strong>Content you provide</strong> — photos, recipes, lists, preferences, and other material you upload while using features such as ${features}.</li>
        <li><strong>Usage data</strong> — app interactions, crash logs, device type, and coarse analytics to improve reliability and performance.</li>
        <li><strong>Camera &amp; photos</strong> — only when you explicitly scan or upload images (e.g. meal photos for recipes). We do not access your library in the background.</li>
      </ul>

      <h2>How we use information</h2>
      <p>We use your data to operate ${app}, personalize results for ${mp.audience.toLowerCase()}, provide core features (${features}), prevent abuse, and improve the product. We do not sell your personal information.</p>

      <h2>AI processing</h2>
      <p>Some features send content you choose (such as food photos) to AI providers to generate recipes or suggestions. That content is processed only to deliver the feature you requested and is not used to train public models without your consent.</p>

      <h2>Sharing</h2>
      <p>We may share data with infrastructure providers (hosting, analytics, AI APIs) under contracts that require them to protect your information. We may disclose data if required by law or to protect users and the service.</p>

      <h2>Retention &amp; deletion</h2>
      <p>We keep account data while your account is active. You may request deletion of your account and associated content via the Support page. Backups may persist for up to 30 days after deletion.</p>

      <h2>Children</h2>
      <p>${app} is not directed to children under 13. We do not knowingly collect data from children.</p>

      <h2>Contact</h2>
      <p>Privacy questions: use the <a href="support">Support page</a> for this app.</p>`);
  }

  if (doc === "terms") {
    return shell("Terms of Service", app, `
      <p><strong>Effective date:</strong> ${new Date().toISOString().slice(0, 10)}</p>
      <p>These Terms of Service ("Terms") govern your use of ${app}. By creating an account or using the app, you agree to these Terms.</p>

      <h2>Using ${app}</h2>
      <p>You must use the app lawfully and in line with its purpose: ${mp.description}</p>
      <ul>
        <li>Do not upload illegal, harmful, or infringing content.</li>
        <li>Do not attempt to reverse-engineer, scrape, or disrupt the service.</li>
        <li>Do not misrepresent AI-generated recipes as professional medical or dietary advice.</li>
      </ul>

      <h2>Your content</h2>
      <p>You retain ownership of photos, recipes, and other content you submit. You grant us a limited license to host, process, and display that content solely to operate ${app} and its features (${features}).</p>

      <h2>AI-generated output</h2>
      <p>Recipes and suggestions may be generated by AI and can be inaccurate. Always verify ingredients, allergens, and cooking safety. ${app} is provided for home cooking inspiration, not professional nutrition or medical guidance.</p>

      <h2>Subscriptions &amp; payments</h2>
      <p>If paid features are offered, pricing and billing terms will be shown before purchase. Unless stated otherwise, subscriptions renew automatically until cancelled in your app store settings.</p>

      <h2>Disclaimer</h2>
      <p>${app} is provided <em>"as is"</em> without warranties of any kind. We do not guarantee uninterrupted or error-free operation.</p>

      <h2>Limitation of liability</h2>
      <p>To the fullest extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from your use of the app.</p>

      <h2>Changes</h2>
      <p>We may update these Terms. Material changes will be communicated in-app or by email. Continued use after changes means you accept the updated Terms.</p>

      <h2>Contact</h2>
      <p>Questions about these Terms: see the Support page for ${app}.</p>`);
  }

  return shell("Support", app, `
    <p>We're here to help you get the most out of <strong>${app}</strong> — built for ${mp.audience.toLowerCase()}.</p>

    <h2>Getting started</h2>
    <ul>
      <li><strong>First launch</strong> — complete the short onboarding, then try the main action on Home (${mp.features[0] ?? "your core feature"}).</li>
      <li><strong>Recipes &amp; lists</strong> — open any recipe for full steps; use <em>Add to shopping list</em> to send ingredients to Lists.</li>
      <li><strong>Scan</strong> — use camera or photo upload to get AI-powered results (requires network).</li>
    </ul>

    <h2>Common questions</h2>
    <ul>
      <li><strong>How do I save a recipe?</strong> Open a recipe and tap <em>Save</em>. Saved count updates in Profile.</li>
      <li><strong>How do I edit dietary preferences?</strong> Profile → Dietary preferences.</li>
      <li><strong>Is my data private?</strong> See our <a href="privacy">Privacy Policy</a>.</li>
      <li><strong>AI looks wrong</strong> — try another photo or edit ingredients manually; AI output is a starting point.</li>
    </ul>

    <h2>Report a problem</h2>
    <p>Include your device model, iOS/Android version, and what you were doing when the issue occurred. Screenshots help.</p>
    <p>Email: <a href="mailto:support@${app.toLowerCase().replace(/[^a-z0-9]/g, "")}.app">support@${app.toLowerCase().replace(/[^a-z0-9]/g, "")}.app</a></p>

    <h2>Response time</h2>
    <p>We aim to reply within 2 business days for free-tier apps. Urgent safety issues (allergens, account access) are prioritized.</p>`);
}
