import type { MasterBuildPrompt } from "@/lib/types";
import { inferCategory } from "@/lib/expoApp/inferCategory";

/**
 * Free per-project legal/support docs — tailored to app domain from the master prompt.
 */
function shell(title: string, app: string, body: string): string {
  const year = new Date().getFullYear();
  return `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title} — ${app}</title>
<style>
  :root{--coral:#FF7A63;--cream:#FDFAF4;--ink:#2B2624;--soft:#5C534F}
  body{margin:0;background:var(--cream);color:var(--ink);
    font-family:ui-sans-serif,system-ui,sans-serif;line-height:1.65}
  .wrap{max-width:720px;margin:0 auto;padding:56px 24px}
  h1{font-size:2rem;margin:0 0 4px}
  .badge{display:inline-block;color:var(--coral);font-weight:600;font-size:.85rem}
  h2{margin-top:2rem;font-size:1.15rem;color:var(--ink)}
  p,li{color:var(--soft);font-size:.95rem}
  a{color:var(--coral)}
  footer{margin-top:48px;font-size:.8rem;color:#8A807A}
</style></head><body><div class="wrap">
<span class="badge">${app}</span>
<h1>${title}</h1>
${body}
<footer>© ${year} ${app} · Generated by Appable · Last updated ${new Date().toISOString().slice(0, 10)}</footer>
</div></body></html>`;
}

function dataCollected(category: ReturnType<typeof inferCategory>, features: string): string {
  const base = `<li><strong>Account information</strong> — email, display name, and authentication identifiers when you create an account.</li>
        <li><strong>Usage data</strong> — app interactions, crash logs, device type, and coarse analytics to improve reliability.</li>`;

  if (category === "pets") {
    return `${base}
        <li><strong>Profile &amp; pet information</strong> — name, neighborhood, dog breed/size, and bio you enter during setup.</li>
        <li><strong>Walk requests &amp; bookings</strong> — dates, locations, budgets, and messages between owners and walkers.</li>
        <li><strong>Payment information</strong> — processed by our payment provider when you book walks (we do not store full card numbers).</li>
        <li><strong>Location</strong> — approximate area you provide for matching walks; we do not track you in the background.</li>`;
  }
  if (category === "cooking") {
    return `${base}
        <li><strong>Content you provide</strong> — photos, recipes, lists, and preferences for features such as ${features}.</li>
        <li><strong>Camera &amp; photos</strong> — only when you scan or upload images for recipes. Not accessed in the background.</li>`;
  }
  if (category === "fitness") {
    return `${base}
        <li><strong>Health &amp; workout data</strong> — workouts logged, goals, and progress you choose to save.</li>`;
  }
  if (category === "shopping") {
    return `${base}
        <li><strong>Orders &amp; cart</strong> — products saved, shipping preferences, and purchase history.</li>`;
  }
  if (category === "social") {
    return `${base}
        <li><strong>Posts &amp; messages</strong> — content you share, follow relationships, and communications in the app.</li>`;
  }
  return `${base}
        <li><strong>Content you provide</strong> — material you create or upload while using ${features}.</li>`;
}

function aiSection(category: ReturnType<typeof inferCategory>): string {
  if (category === "cooking") {
    return `<h2>AI processing</h2>
      <p>Some features send food photos you choose to AI providers to generate recipes or suggestions. Content is processed only to deliver the feature you requested.</p>`;
  }
  if (category === "pets") {
    return `<h2>AI processing</h2>
      <p>If we offer photo or text assistance, content is processed only to deliver the feature you requested — for example helping describe a dog or draft a walk note.</p>`;
  }
  return `<h2>AI processing</h2>
      <p>Some features may send content you choose to AI providers to generate suggestions or complete tasks. That content is processed only to deliver the feature you requested.</p>`;
}

function termsDomain(category: ReturnType<typeof inferCategory>): string {
  if (category === "pets") {
    return `<li>Walkers and owners are independent users — we facilitate matching but do not employ walkers. Owners are responsible for their pets; walkers must follow local laws and owner instructions.</li>
        <li>Do not misrepresent your identity, pet, or qualifications.</li>`;
  }
  if (category === "cooking") {
    return `<li>Do not misrepresent AI-generated recipes as professional medical or dietary advice.</li>`;
  }
  return `<li>Use the app only for its intended purpose and in compliance with applicable laws.</li>`;
}

function contentLicense(category: ReturnType<typeof inferCategory>, app: string, features: string): string {
  if (category === "pets") {
    return `walk requests, messages, and profile information`;
  }
  if (category === "cooking") {
    return `photos, recipes, and lists`;
  }
  return `content you submit related to ${features}`;
}

function supportFaq(category: ReturnType<typeof inferCategory>, app: string, f0: string): string {
  if (category === "pets") {
    return `<h2>Common questions</h2>
    <ul>
      <li><strong>How do I post a walk?</strong> Home → Post a walk request — add breed, area, time, and budget.</li>
      <li><strong>How do walkers get paid?</strong> Profile → Payment to add a payout method. Owners pay when a walk is booked.</li>
      <li><strong>Can I message before booking?</strong> Yes — open a walker profile or request and tap Message.</li>
      <li><strong>Is my data private?</strong> See our <a href="privacy">Privacy Policy</a>.</li>
    </ul>`;
  }
  if (category === "cooking") {
    return `<h2>Common questions</h2>
    <ul>
      <li><strong>How do I save a recipe?</strong> Open a recipe and tap <em>Save</em>.</li>
      <li><strong>How do I add to a shopping list?</strong> Recipe detail → <em>Add to shopping list</em>.</li>
      <li><strong>Is my data private?</strong> See our <a href="privacy">Privacy Policy</a>.</li>
    </ul>`;
  }
  return `<h2>Common questions</h2>
    <ul>
      <li><strong>How do I get started?</strong> Complete onboarding, then try ${f0} on Home.</li>
      <li><strong>How do I save items?</strong> Open any card and tap Save.</li>
      <li><strong>Is my data private?</strong> See our <a href="privacy">Privacy Policy</a>.</li>
    </ul>`;
}

export function legalDoc(
  doc: "privacy" | "terms" | "support",
  mp: MasterBuildPrompt
): string {
  const app = mp.appName;
  const features = mp.features.join(", ");
  const category = inferCategory(mp);
  const f0 = mp.features[0] ?? "your core feature";

  if (doc === "privacy") {
    return shell("Privacy Policy", app, `
      <p><strong>Effective date:</strong> ${new Date().toISOString().slice(0, 10)}</p>
      <p>${app} ("we," "us") respects your privacy. This policy describes what we collect, why we collect it, and the choices you have. It applies to the ${app} mobile application built for ${mp.audience.toLowerCase()}.</p>

      <h2>Information we collect</h2>
      <ul>
        ${dataCollected(category, features)}
      </ul>

      <h2>How we use information</h2>
      <p>We use your data to operate ${app}, deliver features (${features}), personalize the experience for ${mp.audience.toLowerCase()}, prevent abuse, and improve the product. We do not sell your personal information.</p>

      ${aiSection(category)}

      <h2>Sharing</h2>
      <p>We may share data with infrastructure providers (hosting, analytics, payment, AI APIs) under contracts that require them to protect your information. We may disclose data if required by law or to protect users and the service.</p>

      <h2>Retention &amp; deletion</h2>
      <p>We keep account data while your account is active. You may request deletion via the Support page. Backups may persist for up to 30 days after deletion.</p>

      <h2>Children</h2>
      <p>${app} is not directed to children under 13.</p>

      <h2>Contact</h2>
      <p>Privacy questions: use the <a href="support">Support page</a> for this app.</p>`);
  }

  if (doc === "terms") {
    return shell("Terms of Service", app, `
      <p><strong>Effective date:</strong> ${new Date().toISOString().slice(0, 10)}</p>
      <p>These Terms govern your use of ${app}. By creating an account or using the app, you agree to these Terms.</p>

      <h2>Using ${app}</h2>
      <p>You must use the app lawfully and in line with its purpose: ${mp.description}</p>
      <ul>
        <li>Do not upload illegal, harmful, or infringing content.</li>
        <li>Do not attempt to reverse-engineer, scrape, or disrupt the service.</li>
        ${termsDomain(category)}
      </ul>

      <h2>Your content</h2>
      <p>You retain ownership of content you submit. You grant us a limited license to host, process, and display ${contentLicense(category, app, features)} solely to operate ${app}.</p>

      <h2>AI-generated output</h2>
      <p>Suggestions generated by AI may be inaccurate. Always verify important details before relying on them.</p>

      <h2>Payments</h2>
      <p>If the app includes bookings or purchases, pricing and billing terms are shown before you pay. Subscriptions renew until cancelled in your app store settings where applicable.</p>

      <h2>Disclaimer</h2>
      <p>${app} is provided <em>"as is"</em> without warranties of any kind.</p>

      <h2>Contact</h2>
      <p>Questions: see the Support page for ${app}.</p>`);
  }

  return shell("Support", app, `
    <p>We're here to help you get the most out of <strong>${app}</strong> — built for ${mp.audience.toLowerCase()}.</p>

    <h2>Getting started</h2>
    <ul>
      <li><strong>First launch</strong> — ${category === "pets" ? "pick Dog owner or Dog walker, complete your profile, then browse or post walks." : `complete onboarding, then try ${f0} on Home.`}</li>
      <li><strong>Core features</strong> — ${features}.</li>
    </ul>

    ${supportFaq(category, app, f0)}

    <h2>Report a problem</h2>
    <p>Include your device model, OS version, and what you were doing. Screenshots help.</p>
    <p>Email: <a href="mailto:support@${app.toLowerCase().replace(/[^a-z0-9]/g, "")}.app">support@${app.toLowerCase().replace(/[^a-z0-9]/g, "")}.app</a></p>

    <h2>Response time</h2>
    <p>We aim to reply within 2 business days.</p>`);
}
