/**
 * Windows path: generate codemagic.yaml so the user can build in the cloud and
 * install via internal TestFlight on their iPhone (no local Xcode needed).
 */
import type { MasterBuildPrompt } from "./types.js";

export function generateCodemagicYaml(prompt: MasterBuildPrompt, app: string): string {
  return `# Generated by Appable Builder — cloud build for Windows users.
# Connect your (free) Codemagic account, push this project, and run this workflow.
workflows:
  appable-ios:
    name: ${prompt.appName} (iOS)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "${app}.xcodeproj"
        XCODE_SCHEME: "${app}"
        BUNDLE_ID: "com.appable.${prompt.appName.toLowerCase().replace(/[^a-z0-9]/g, "")}"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install XcodeGen
        script: brew install xcodegen
      - name: Generate Xcode project
        script: xcodegen generate
      - name: Build & archive
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" \\
            -sdk iphoneos -configuration Release archive \\
            -archivePath build/${app}.xcarchive \\
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/**/*.xcarchive
    # To deliver to your iPhone via internal TestFlight, add your App Store
    # Connect API key in Codemagic and uncomment:
    # publishing:
    #   app_store_connect:
    #     auth: integration
    #     submit_to_testflight: true
`;
}

/** The step-by-step guided flow shown in chat for Windows users. */
export function codemagicGuide(prompt: MasterBuildPrompt): string[] {
  return [
    "You're on Windows, so we'll build your app in the cloud — it'll land on your iPhone.",
    "1. Create a free account at codemagic.io and sign in with GitHub.",
    `2. I've added a codemagic.yaml to your ${prompt.appName} project — push the project to a new GitHub repo.`,
    "3. In Codemagic, add the repo and pick the 'Appable iOS' workflow.",
    "4. Add your Apple ID / App Store Connect API key when prompted (one-time).",
    "5. Hit Start build — when it finishes, accept the TestFlight invite on your iPhone.",
    "That's it — open TestFlight and your app is there. 🎉",
  ];
}
